spark.sql.extensions                         org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.iceberg                    org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.type               hive
spark.sql.catalog.iceberg.uri                thrift://hive-metastore:9083
spark.sql.catalog.iceberg.warehouse          s3a://warehouse/iceberg

spark.sql.catalog.polaris                    org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.polaris.catalog-impl       org.apache.iceberg.rest.RESTCatalog
spark.sql.catalog.polaris.uri                http://polaris:8181/api/catalog
spark.sql.catalog.polaris.warehouse          lakehouse
spark.sql.catalog.polaris.credential         admin:pass1234
spark.sql.catalog.polaris.scope              PRINCIPAL_ROLE:ALL
spark.sql.catalog.polaris.token-refresh-enabled true
spark.sql.catalog.polaris.header.X-Iceberg-Access-Delegation vended-credentials

spark.hadoop.fs.s3a.impl                     org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint                 http://minio:9000
spark.hadoop.fs.s3a.access.key               admin
spark.hadoop.fs.s3a.secret.key               pass1234
spark.hadoop.fs.s3a.path.style.access        true
spark.hadoop.fs.s3a.connection.ssl.enabled   false
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
